### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by easella** [EnderKingJ/VoidNet#2]
![image](https://user-images.githubusercontent.com/74786054/114669140-919bc400-9ccf-11eb-9c8c-647b3b5d7ec6.png)

**Comment by s-tn** [comment]
fixed in newest deployment. Use the Ludicrous version for better support

**Comment by easella** [comment]
still does not work
![image](https://user-images.githubusercontent.com/74786054/115809449-21b9c780-a3ba-11eb-9775-016e48eb4f46.png)
